### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ITLoveURURI** [kamiras/kamiras-ssh-botnet#1]
File "ataque.py", line 42
    +---> Bot {[i]}: IP:{ip_equipos[i]} USER:{user_equipos[i]} PASS={password_equipos[i]}''')

 File "ssh.py", line 49
    print(f'[*] Authentication Worked IP:{ip} USER:{USER[i]} PASS={PASS[i]}')
                                                                           ^
SyntaxError: invalid syntax

**Comment by kamiras** [comment]
Did you install paramiko? That is a Python implementation of SSH. If you didn't install it, just install it : pip install paramiko
If you got it installed give me more details about the problem please.

**Comment by kamiras** [comment]
Ok just realised what's the error ( I think ). You were using *sudo python ssh.py* right? Just use *python ssh.py*
