### ISSUE TITLE
what's ataque.py

### ISSUE THREAD

**Issue by pwned4ever2** [kamiras/kamiras-ssh-botnet#3]
Is it the bot file

**Comment by kamiras** [comment]
ataque.py contains all the functions that the program needs to work. For example, it cointains :

- SSH Brute Force Attack **function**
- Command Execution **function**
- HTTP/HTTPS Attack **function**
- PING Attack **function**
- SYN Attack **function**
- ACK Attack **function**
- Bots Alive Function **function**
- File Uploading via SSH **function**

Q: Is it the bot file : Yes
